authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('update/', authapp.update, name='update'),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('products/', mainapp.products, name='products'),
    path('contact/', mainapp.contact, name='contact'),
]

authapp/models.py
from django.db import models

from django.contrib.auth.models import User, AbstractUser


class ShopUser(AbstractUser):
    age = models.PositiveSmallIntegerField(verbose_name='возраст', null=True)
    avatar = models.ImageField(upload_to='users_avatars', blank=True)

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField('имя категории', max_length=64)
    description = models.TextField('описание категории', blank=True)

    def __str__(self):
        return f'{self.name}'


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
import django.forms as forms

from authapp.models import ShopUser


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = f'form-control {field_name}'


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = (
            'username', 'password1', 'password2', 'email',
            'first_name', 'last_name', 'age', 'avatar'
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = f'form-control {field_name}'
            field.help_text = ''


class ShopUserUpdateForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = (
            'username', 'password', 'email', 'first_name',
            'last_name', 'age', 'avatar'
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'password':
                field.widget = forms.HiddenInput()
            else:
                field.widget.attrs['class'] = f'form-control {field_name}'
                field.help_text = ''

authapp/views.py
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from authapp.forms import ShopUserLoginForm, ShopUserRegisterForm, ShopUserUpdateForm


def login(request):
    if request.method == 'POST':
        form = ShopUserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = ShopUserLoginForm()
    context = {
        'title': 'вход в сиcтему',
        'form': form,
    }
    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main:index'))


def register(request):
    if request.method == 'POST':
        form = ShopUserRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = ShopUserRegisterForm()
    context = {
        'title': 'регистрация пользователя',
        'form': form,
    }
    return render(request, 'authapp/register.html', context)


def update(request):
    if request.method == 'POST':
        form = ShopUserUpdateForm(request.POST, request.FILES,
                                  instance=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('auth:update'))
    else:
        form = ShopUserUpdateForm(instance=request.user)
    context = {
        'title': 'профиль пользователя',
        'form': form,
    }
    return render(request, 'authapp/update.html', context)

mainapp/views.py
from django.shortcuts import render
from mainapp.models import ProductCategory, Product


# возвращает результат рендеринга html файла, указываем относительный путь от папки templates
# удерживая клавишу Ctrl появляется рука можем посмотреть файл
def index(request):
    context = {
        'page_title': 'главная'
    }
    return render(request, 'mainapp/index.html', context)


def products(request):
    categories = ProductCategory.objects.all()
    products = Product.objects.all()
    context = {
        'page_title': 'продукты',
        'categories': categories,
        'products': products,
    }
    return render(request, 'mainapp/products.html', context)


def contact(request):
    locations = [
        {
            'city': 'Москва',
            'phone': '+7-800-495-5555',
            'email': 'info@geekshop.ru',
            'address': 'Ленинский проспект, дом 2',
        },
        {
            'city': 'Санкт-Петербург',
            'phone': '+7-812-800-4444',
            'email': 'hello@geekshop.ru',
            'address': 'ул., Айвазовского, дом 10',
        },
        {
            'city': 'Красноярск',
            'phone': '+7-800-800-3333',
            'email': 'menendger@geekshop.ru',
            'address': 'ул, Ленина, дом 1',
        },
    ]

    context = {
        'page_title': 'контакты',
        'locations': locations,
    }
    return render(request, 'mainapp/contact.html', context)

authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {{ title|capfirst }}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static '/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}

    {% endblock %}
</head>
<body>
<div class="container">
    <div class="login">
        {% block container %}
        {% endblock %}
    </div>
</div>
</body>
</html>

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block container %}
    <div class="h2 text-center head">
        Вход в систему
    </div>
    <form class="form-horizontal" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input class="form-control" type="submit" value="войти">
    </form>
    <a href="{% url 'auth:register' %}"
       class="btn btn-round form-control">
        зарегистрироваться
    </a>

{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block container %}
    <div class="h2 text-center head">
        Регистрация пользователя
    </div>
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input class="form-control" type="submit" value="зарегистрироваться">
    </form>

{% endblock %}

authapp/templates/authapp/update.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block container %}
    <div class="h2 text-center head">
        Профиль пользователя
    </div>
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input class="form-control" type="submit" value="сохранить">
    </form>
    <a class="btn btn-default" href="{% url 'main:index' %}">на главную</a>

{% endblock %}

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    {% block title %}
        <title>
            {{ page_title|title }}
        </title>
    {% endblock %}
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
<div class="container">
    {% block container %}
    {% endblock %}
    <div class="clr"></div>
</div>

{% block footer %}
    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB {% now "Y" %}</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
    </div>
{% endblock %}
</body>
</html>

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block container %}
    <div class="hero">
        {% include 'mainapp/includes/inc__main_menu.html' %}
        <h1>наши контакты</h1>
    </div>

    <div class="location">
        {% if locations %}
            {% for item in locations %}
                <div class="location-1">
                    <i class="fa fa-map-marker fa-5x"></i>
                    <h4>{{ item.city }}</h4>
                    <div class="contacts">
                        <h5>Телефон</h5>
                        <p>{{ item.phone }}</p>
                    </div>
                    <div class="contacts">
                        <h5>Email</h5>
                        <p>{{ item.email }}</p>
                    </div>
                    <div class="contacts">
                        <h5>Адрес</h5>
                        <p>{{ item.address }}</p>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

mainapp/templates/mainapp/includes/inc__category_menu.html
<div class="links clearfix">
    <ul class="links-menu">
        <li><a href="#" class="active">все</a></li>

        {% for category in categories %}
            <li>
                <a href="#">
                    {{ category.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
</div>

mainapp/templates/mainapp/includes/inc__main_menu.html
<div class="header clearfix">
    <a href="{% url 'main:index' %}" class="logo"></a>
    <ul class="menu">
        <li>
            <a href="{% url 'main:index' %}" class="active">
                домой
            </a>
        </li>
        <li>
            <a href="{% url 'main:products' %}">
                продукты
            </a>
        </li>
        <li>
            <a href="{% url 'main:contact' %}">
                контакты
            </a>
        </li>
        {% if user.is_authenticated %}
            <li>
                <a href="{% url 'auth:update' %}">
                    {{ user.first_name|default:'пользователь'|title }}
                </a>
            </li>
        {% endif %}
        <li>
            {% if user.is_authenticated %}
                <a href="{% url 'auth:logout' %}">
                    выход
                </a>
            {% else %}
                <a href="{% url 'auth:login' %}">
                    вход
                </a>
            {% endif %}
        </li>
    </ul>
    <a href="#" class="search"></a>
    <a href="#" class="basket"></a>
</div>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block container %}
    <div class="slider">
        {% include 'mainapp/includes/inc__main_menu.html' %}
        <div class="text-slider">
            <h3 class="green">тенденции</h3>
            <h3 class="big"> удобные стулья</h3>
            <p>Новый уровень комфорта. Отличные характеристики.</p>
            <a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
        </div>
        <div class="navi">
            <a href="#"></a><a href="#"></a><a href="#"></a>
        </div>
    </div>

    <div class="featured">
        <div class="featured-menu">
            <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
        </div>
        <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
        <div class="clearfix">
        </div>
        <div class="tab-content">
            <div class="block">
                <a href="#"><img src="{% static 'img/product-1.jpg' %}" alt="">
                    <div class="text">
                        <img src="{% static 'img/icon-hover.png' %}" alt="img">
                        <h4>Отличный стул</h4>
                        <p>Расположитесь комфортно. </p>
                    </div>
                </a>
            </div>
            <div class="block">
                <a href="#"><img src="{% static 'img/product-2.jpg' %}" alt="">
                    <div class="text">
                        <img src="{% static 'img/icon-hover.png' %}" alt="">
                        <h4>Стул повышенного качества</h4>
                        <p>Не оторваться. </p>
                    </div>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block container %}
    <div class="hero-white">
        {% include 'mainapp/includes/inc__main_menu.html' %}
    </div>

    <div class="details">
        {% include 'mainapp/includes/inc__category_menu.html' %}

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="{% static 'img/slider1.jpg' %}" alt="">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#"><img src="{% static 'img/controll.jpg' %}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="{% static 'img/controll1.jpg' %}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="{% static 'img/controll2.jpg' %}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">Отличный стул</h3>
                <h3 class="red">горячее предложение</h3>
                <p class="price"> 2585.9 <span>руб</span></p>
                <a href="#" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    <p>Расположитесь комфортно.</p>
                    <p>Отличное качество материалов
                        позволит вам это.</p>
                    <p>Различные цвета</p>
                    <p>высочайший уровень
                        эргономики и прочность.</p>
                </div>
            </div>
        </div>

        <div class="related">
            <div class="title clearfix">
                <h2>Похожие продукты</h2>
                <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
            </div>
            <div class="related-products clearfix">
                {% for product in products %}

                    <div class="block">
                    <a href="#"><img src="{{ product.image.url}}" alt="">
                        <div class="text">
                        <img src="{% static 'img/icon-hover.png' %}" alt="img">
                        <h4>{{ product.name }}</h4>
                            <p>{{ product.short_desc }} </p>
                        </div>
                    </a>
                </div>
            {% endfor %}

            </div>
        </div>
    </div>
{% endblock %}